// Compile this file to verify all static_assert(sizeof(...)) in the RE headers.
// Open RE/.build/ in Visual Studio via CMake and build — any size mismatch
// will be a compile error.

#include "CryEngine/CryCommon/BaseTypes.h"   // uint64 etc. needed by CryGUID.h

#include "rpgmodule/C_Soul.h"                // pulls in most rpgmodule headers
#include "rpgmodule/C_RPGModule.h"
#include "rpgmodule/C_Effect.h"
#include "rpgmodule/S_RpgParams.h"
#include "rpgmodule/S_PerkPointCounters.h"
#include "crysystem/CXConsole.h"
#include "crysystem/CLog.h"
#include "crysystem/CScriptSystem.h"
#include "framework/I_Action.h"
#include "framework/I_ActionImpl.h"
#include "framework/C_BaseModule.h"
#include "framework/WuidRegistries.h"
#include "framework/C_ReadinessObserver.h"
#include "framework/I_ReadinessTask.h"
#include "framework/C_CrySaveGameHelper.h"
#include "framework/C_CryLoadGameHelper.h"
#include "framework/C_PlayerProfileWHManager.h"
#include "framework/C_SaveGameManager.h"
#include "game/S_GameContext.h"
#include "animationmodule/C_AnimationDatabase.h"
#include "animationmodule/I_SceneListener.h"
#include "entitymodule/I_ItemAttachmentListener.h"
#include "entitymodule/C_Item.h"
#include "entitymodule/S_ItemData.h"
#include "entitymodule/C_ItemRuntimeData.h"
#include "entitymodule/C_Inventory.h"
#include "entitymodule/C_EquipmentManager.h"
#include "combatmodule/I_CombatActor.h"
#include "combatmodule/I_CombatActorAction.h"
#include "combatmodule/C_CombatComboData.h"
#include "combatmodule/C_CombatDatabase.h"
#include "combatmodule/C_CombatModule.h"
#include "combatmodule/C_CombatScene.h"
#include "combatmodule/C_CombatActor.h"
#include "framework/C_ActionDirector.h"
#include "combatmodule/C_CombatActorDirector.h"
#include "combatmodule/I_CombatTarget.h"
#include "combatmodule/S_CombatActorState.h"
#include "combatmodule/C_CombatActorObject.h"
#include "combatmodule/C_CombatActorUpdatedObject.h"
#include "combatmodule/C_CombatTrigger.h"
#include "combatmodule/C_CombatSlotTrigger.h"
#include "combatmodule/C_CombatTriggerCombo.h"
#include "combatmodule/C_CombatTriggerPerfectBlock.h"
#include "combatmodule/C_CombatTriggerRiposte.h"
#include "combatmodule/C_CombatTriggerSyncPerfectBlock.h"
#include "combatmodule/C_CombatTriggerSyncRiposte.h"
#include "combatmodule/C_CombatTriggerSyncDodge.h"
#include "combatmodule/C_CombatComboManager.h"
#include "combatmodule/C_CombatActionFactory.h"
#include "combatmodule/C_CombatActorActionManager.h"
#include "combatmodule/C_CombatActorHuntAttack.h"
#include "combatmodule/C_CombatActorHorsePullDown.h"
#include "combatmodule/C_CombatActorMercyKill.h"
#include "combatmodule/C_CombatActorActionT.h"
#include "combatmodule/S_CombatActorActionAttackParams.h"
#include "combatmodule/S_CombatActorActionStaticAttackParams.h"
#include "combatmodule/S_CombatActorActionSyncAttackParams.h"
#include "combatmodule/S_CombatActorActionBlockParams.h"
#include "combatmodule/S_CombatActorActionPerfectBlockParams.h"
#include "combatmodule/S_CombatActorActionComposedRipostePerfectBlockParams.h"
#include "combatmodule/S_CombatActorActionHitParams.h"
#include "combatmodule/S_CombatActorActionFreeBlockParams.h"
#include "combatmodule/S_CombatActorActionBlockTriggerParams.h"
#include "combatmodule/S_CombatActorActionGuardParams.h"
#include "combatmodule/S_CombatActorActionGuardMovementParams.h"
#include "combatmodule/S_CombatActorActionGuardSyncMovementParams.h"
#include "combatmodule/S_CombatActorActionSyncHitParams.h"
#include "combatmodule/S_CombatActorActionSyncPerfectBlockHitParams.h"
#include "combatmodule/S_CombatActorActionSyncTransitionParams.h"
#include "combatmodule/S_CombatActorActionPoseModifierParams.h"
#include "combatmodule/C_CombatActionHelper.h"
#include "combatmodule/I_CombatActorActionBlock.h"
#include "combatmodule/I_CombatActionHelperOwner.h"
#include "combatmodule/C_CombatActorActionAttack.h"
#include "combatmodule/C_CombatActorActionStaticAttack.h"
#include "combatmodule/C_CombatActorActionSyncAttack.h"
#include "combatmodule/C_CombatActorActionBlock.h"
#include "combatmodule/C_CombatActorActionBlockTrigger.h"
#include "combatmodule/C_CombatActorActionFreeBlock.h"
#include "combatmodule/C_CombatActorActionPerfectBlock.h"
#include "combatmodule/C_CombatActorActionComposedRipostePerfectBlock.h"
#include "combatmodule/C_CombatActorActionSyncPerfectBlock.h"
#include "combatmodule/C_CombatActorActionSyncPerfectBlockHit.h"
#include "combatmodule/C_CombatActorActionHit.h"
#include "combatmodule/C_CombatActorActionSyncHit.h"
#include "combatmodule/C_CombatActorActionSyncTransition.h"
#include "combatmodule/C_CombatActorActionGuard.h"
#include "combatmodule/C_CombatActorActionGuardMovement.h"
#include "combatmodule/C_CombatActorActionGuardSyncMovement.h"
#include "combatmodule/C_CombatActorActionRiderMovement.h"
#include "combatmodule/C_CombatActorActionPoseModifier.h"
#include "combatmodule/S_CombatSettings.h"
#include "entitymodule/C_Player.h"
#include "Offsets/vtables/IGameObject.h"
#include "Offsets/vtables/IActorSystem.h"
#include "Offsets/vtables/IEntitySystemSink.h"
#include "Offsets/vtables/IEntityEventListener.h"
#include "xgenaimodule/BehaviorTree/I_Node.h"
#include "xgenaimodule/BehaviorTree/I_DebugNode.h"
#include "xgenaimodule/BehaviorTree/C_Node.h"
#include "xgenaimodule/BehaviorTree/C_Decorator.h"
#include "xgenaimodule/BehaviorTree/C_Composite.h"
#include "xgenaimodule/BehaviorTree/C_Composites.h"
#include "xgenaimodule/BehaviorTree/C_Gate.h"
#include "xgenaimodule/BehaviorTree/C_NodeWrapper.h"
#include "xgenaimodule/BehaviorTree/C_NodeContext.h"
#include "xgenaimodule/BehaviorTree/C_Barrier.h"
#include "xgenaimodule/BehaviorTree/bt/C_RemoveItem.h"
#include "xgenaimodule/BehaviorTree/bt/C_AddBuff.h"
#include "xgenaimodule/BehaviorTree/bt/C_VarOperation.h"
#include "rpgmodule/buff/C_BuffInstanceBase.h"
#include "rpgmodule/buff/C_SoulBuffInstance.h"
#include "rpgmodule/buff/C_ConstantSoulBuffInstance.h"
#include "rpgmodule/buff/C_TimedSoulBuffInstance.h"
#include "rpgmodule/buff/C_BuffManager.h"
#include "framework/C_HashMap.h"
#include "framework/S_TypeFactoryEntry.h"
#include "rpgmodule/buff/C_BuffFactory.h"
#include "rpgmodule/buff/C_BuffInitParamsDefault.h"
#include "rpgmodule/buff/C_InjuredBuffInitParams.h"
#include "rpgmodule/buff/C_SleepBuffInitParams.h"
#include "rpgmodule/buff/C_MoraleContextBuffInitParams.h"
#include "rpgmodule/buff/C_ItemHealthCheckingBuffInitParams.h"
#include "xgenaimodule/C_AIObject.h"
#include "xgenaimodule/C_LinkableObject.h"
#include "xgenaimodule/C_MessageCapableObject.h"
#include "xgenaimodule/C_IntelligentObject.h"
#include "xgenaimodule/C_LinkablesManager.h"
#include "xgenaimodule/C_IntelligentObjectManager.h"
#include "xgenaimodule/EntityToAIMap.h"
#include "xgenaimodule/C_AIPuppet.h"
#include "xgenaimodule/S_InformationRecord.h"
#include "xgenaimodule/C_InformationManager.h"

// ---- RTTI / kcd_cast smoke test ----
#include "Offsets/RTTI.h"
namespace {
    [[maybe_unused]] void rtti_smoke_test() {
        wh::framework::I_Action* base = nullptr;
        // downcast across the inheritance chain using the game's own RTTI
        auto* hit  = kcd_cast<wh::combatmodule::C_CombatActorActionSyncHit*>(base);
        auto* atk  = kcd_cast<wh::combatmodule::C_CombatActorActionSyncAttack*>(base);
        // sibling/unrelated cast must also compile (returns nullptr at runtime)
        wh::combatmodule::C_CombatActor* actor = nullptr;
        auto* soul = kcd_cast<wh::rpgmodule::C_Soul*>(actor);
        (void)hit; (void)atk; (void)soul;
    }
}
