// Compile this file to verify all static_assert(sizeof(...)) in the RE headers.
// Open RE/.build/ in Visual Studio via CMake and build — any size mismatch
// will be a compile error.

#include "CryEngine/CryCommon/BaseTypes.h"   // uint64 etc. needed by CryGUID.h

#include "rpgmodule/C_Soul.h"                // pulls in most rpgmodule headers
#include "rpgmodule/C_RPGModule.h"
#include "rpgmodule/C_Effect.h"
#include "rpgmodule/S_RpgParams.h"
#include "rpgmodule/S_PerkPointCounters.h"
#include "crysystem/CXConsole.h"
#include "crysystem/CLog.h"
#include "crysystem/CScriptSystem.h"
#include "framework/I_Action.h"
#include "framework/I_ActionImpl.h"
#include "framework/C_BaseModule.h"
#include "animationmodule/C_AnimationDatabase.h"
#include "animationmodule/I_SceneListener.h"
#include "entitymodule/I_ItemAttachmentListener.h"
#include "combatmodule/I_CombatActor.h"
#include "combatmodule/I_CombatActorAction.h"
#include "combatmodule/C_CombatComboData.h"
#include "combatmodule/C_CombatDatabase.h"
#include "combatmodule/C_CombatModule.h"
#include "combatmodule/C_CombatScene.h"
#include "combatmodule/C_CombatActor.h"
#include "combatmodule/I_CombatTarget.h"
#include "combatmodule/S_CombatActorState.h"
#include "combatmodule/C_CombatActorObject.h"
#include "combatmodule/C_CombatActorUpdatedObject.h"
#include "combatmodule/C_CombatTrigger.h"
#include "combatmodule/C_CombatSlotTrigger.h"
#include "combatmodule/C_CombatTriggerCombo.h"
#include "combatmodule/C_CombatTriggerPerfectBlock.h"
#include "combatmodule/C_CombatTriggerRiposte.h"
#include "combatmodule/C_CombatTriggerSyncPerfectBlock.h"
#include "combatmodule/C_CombatTriggerSyncRiposte.h"
#include "combatmodule/C_CombatTriggerSyncDodge.h"
#include "combatmodule/C_CombatComboManager.h"
#include "combatmodule/C_CombatActionFactory.h"
#include "combatmodule/C_CombatActorActionManager.h"
#include "combatmodule/S_CombatSettings.h"
#include "entitymodule/C_Player.h"
#include "Offsets/vtables/IGameObject.h"
#include "Offsets/vtables/IActorSystem.h"
#include "Offsets/vtables/IEntitySystemSink.h"
#include "Offsets/vtables/IEntityEventListener.h"
